using System.Collections;
using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.SceneManagement;

public class Credits : MonoBehaviour
{
    [SerializeField] TextMeshProUGUI creditsTxt;

    private void Start() {
        GetCredits();
    }
    public void ReturnToMainScene(){
        SceneManager.LoadScene("MainMenu");
    }
    public void GetCredits(){
        string author = "Game made by Michal Borodulin\n";
        string font = "Used font: \"Dune Rise\" by Fontswan, available online at dafont.com\n";
        string images="Used images were mostly generated by AI. Specifically using sites: firely.adobe.com and freepic.com\n";
        string voicelines="Sound were generated by AI through site Play.ht\n";
        string everythingElse="Everything else was made by Michal Borodulin.\n";
        string credits="Project made as part of bachelor degree course in University of Lodz.";

        creditsTxt.text = author+font+images+voicelines+everythingElse+credits;

    }
    
}
